#!/usr/bin/perl -w
#Diskutilo

use strict;
use warnings;

use Data::Dumper;
use jabber;
use gui_glade;
use XML::Simple qw(:strict);

my $diskutilo = main->new;
$diskutilo->{config} = $diskutilo->read_config("config");
$diskutilo->{gui} = gui_glade->new($diskutilo->{config}->{gui}, $diskutilo);
if(defined($diskutilo->{config}->{accounts})) {
    foreach (keys(%{$diskutilo->{config}->{accounts}})) {
	$diskutilo->add_account($_, $diskutilo->{config}->{accounts}->{$_});
    }
}
$diskutilo->{gui}->main;
exit 0;


package main;
#GLOBAL
sub new
{
    my ($class) = @_;
    my $this = {};
    bless($this, $class);

    return $this;
}

sub set_global_state {
    my ($this, $state) = @_;
    $this->set_account_state($_, $state) foreach (keys(%{$this->{jabber}}));
}

#CONFIG
sub read_config {
    my ($this, $file_name) = @_;
    if (-e $file_name) {
	$this->{config} = XMLin($file_name, ForceArray => 1, KeyAttr => "key");
    }
}

#ACCOUNT
sub add_account {
    my ($this, $ajid, $config) = @_;
    $this->{jabber}->{$ajid} = jabber->new($config, $this);
    $this->{gui}->add_account($ajid, $config->{name});
}

sub set_account_state {
    my ($this, $ajid, $state) = @_;
    return -1 if(!defined($this->{jabber}->{$ajid}));
    $this->{jabber}->{$ajid}->set_state($state, "");
    $this->{gui}->set_account_state($ajid, $state, sub { $this->{jabber}->{$ajid}->{connection}->Process(0);1});
    return 0;
}

#CONTACT
sub get_contact_roster_info {
    my ($this, $ajid, $jid) = @_;
    return ($this->{jabber}->{$ajid}->{roster}->{$jid}->{name});
}

sub send_chat {
    my ($this, $ajid, $jid, $body) = @_;
    $this->{jabber}->{$ajid}->send_chat($jid, $body);
}

sub on_contact_message {
    my ($this, $ajid, $fjid, $type, $body, $subject) = @_;

    $this->{gui}->on_chat($ajid, $fjid, $body) if($type eq "chat");
    $this->{gui}->on_message($ajid, $fjid, $subject, $body) if($type eq "message");
    $this->{gui}->on_headline($ajid, $fjid, $subject, $body) if($type eq "headline");
}

sub on_contact_presence {
    my ($this, $ajid, $fjid, $state) = @_;
    $this->{gui}->on_contact_presence($ajid, $fjid, $state);
}

1;
